# Generated by Django 3.2.9 on 2021-12-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20211202_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='Альбом'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
